//
// Created by taeguk on 2017-04-05.
//

#ifndef EMBEDDED_SYSTEM_SOFTWARE_ASSIGNMENT_MODE_EXTRA_H
#define EMBEDDED_SYSTEM_SOFTWARE_ASSIGNMENT_MODE_EXTRA_H

#endif //EMBEDDED_SYSTEM_SOFTWARE_ASSIGNMENT_MODE_EXTRA_H
