//
// Created by taeguk on 2017-04-06.
//

#ifndef EMBEDDED_SYSTEM_SOFTWARE_ASSIGNMENT_MYTIME_H
#define EMBEDDED_SYSTEM_SOFTWARE_ASSIGNMENT_MYTIME_H

long get_nano_realtime ();

#endif //EMBEDDED_SYSTEM_SOFTWARE_ASSIGNMENT_MYTIME_H
